import pyautogui
import time
from random import randint

for i in range(10):
    x, y = randint(0,1000), randint(0,1000)  
    pyautogui.moveTo(x, y, duration=0.5)  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='left')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='right')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='left')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='right')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='left')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='right')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='left')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='right')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='left')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='right')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='left')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='right')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='left')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='right')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='left')  
    time.sleep(0.5)  
    pyautogui.click(x=x, y=y, button='right')  
    time.sleep(0.5)
